name: ⏰ Daily Sentiment Data Update

on:
  schedule:
    - cron: '0 1 * * *'  # 9 AM UTC daily
  workflow_dispatch:

env:
  USER: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}
  HOST: ${{ secrets.HOST }}
  PORT: ${{ secrets.PORT }}
  DBNAME: ${{ secrets.DBNAME }}

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Reddit Extraction
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
        run: python reddit_extraction.py

      - name: Run YouTube Extraction
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python youtube_extraction.py

      - name: Run News Extraction
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python news_extraction.py
